### PR TITLE
Standardize avatar size on Users page.

### PR DESCRIPTION
**Pull request by ListenerJubatus**
Addressing https://github.com/GetLuna/Luna/issues/1239

### CODE REVIEW

**Comment by Studio384** [comment]
Thanks for the fix.

**Comment by Quy** [comment]
An issue I see here is what if the board default dimensions are not 100x100.

**Comment by Studio384** [comment]
Perhaps putting the avatar in a container that is 100x100 and center the image in case its smaller is a better solution.

**Comment by Quy** [comment]
Yes, however, but it won't fix when Max width and Max height settings that are not 100x100.

**Comment by Studio384** [comment]
Why wouldn't it? If it isn't 100x100, for example 80x80, it will just leave 10 pixels open on each side, as if you uploaded a 80x80 avatar when set to 100x100.

**Comment by Quy** [comment]
What if I want the avatar default settings to be 150x150 or larger? It will be reduced to 100x100.

**Comment by Quy** [comment]
On the other hand, I guess on the userlist it will be forced to be 100x100 independent of the default settings.

**Comment by Studio384** [comment]
Yes, it will be forced. Basically, when the settings is lower then 100x100 or the uploaded avatar is smaller, it should be centered in a 100x100 square in the user list. Anything above should be shrunk down to 100x100 max. I don't think anyone would want to see avatars of a 200x200 size in the userlist.

**Pull request closed without merging**
